### ISSUE TITLE
OS X Atom Shell dependency named "Julia"

### ISSUE THREAD

**Issue by lilinjn** [one-more-minute/Blink.jl#3]
Hi -- Blink.jl is fun stuff.  Why exactly is Mac OS X atom shell executable called "Julia" and located in deps/Julia.app/Contents/MacOS?  Is this executable a vanilla atomshell binary or is there some sort of customization that you had to do -- can you describe whatever customizations you had to do?

**Comment by one-more-minute** [comment]
It's just a build of Atom Shell with a custom name/icon. The atom shell docs give instructions on getting the rename and stuff, but if you wanted to just change `Julia` to `Atom` and use the original Atom.app that'd work fine too.

**Comment by lilinjn** [comment]
Thanks -- Sounds good.  I was mostly curious in case there was something more complicated going on.
