### ISSUE TITLE
Register in METADATA

### ISSUE THREAD

**Issue by sjkelly** [one-more-minute/Blink.jl#4]
It would be nice to have this package registered in METADATA.jl in the future.

**Comment by one-more-minute** [comment]
Am I going crazy or is it [there already](https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/Blink)? Or did you mean something else? I haven't tagged a version in a while, I would like to but it needs a bit more testing, I think.

**Comment by sjkelly** [comment]
Wow, apologies! I completely missed that.

**Comment by one-more-minute** [comment]
No problem!
